# Generated by Django 3.0.8 on 2021-02-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
